using OpenIddict.Abstractions;

using Microsoft.AspNetCore;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyRemoteApi.Data;
using MyRemoteApi.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

using Microsoft.EntityFrameworkCore;
using MyRemoteApi.Data;
using System.Reflection;
using Microsoft.AspNetCore.Identity;


var builder = WebApplication.CreateBuilder(args);


// Add Database Connection
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
var defaultConnectionString = connectionString;


builder.WebHost.ConfigureKestrel(serverOptions =>
{
    string x = " not...";
    Console.WriteLine("Are we configuring kestrel?");
    serverOptions.ConfigureHttpsDefaults(httpsOptions => // listenOptions =>
    {
        x = " so...?";
        httpsOptions.ClientCertificateMode = Microsoft.AspNetCore.Server.Kestrel.Https.ClientCertificateMode.RequireCertificate;
        httpsOptions.CheckCertificateRevocation = true;
        httpsOptions.SslProtocols = System.Security.Authentication.SslProtocols.Tls12 | System.Security.Authentication.SslProtocols.Tls13;
        Console.WriteLine("----");
        x = " so";
/*
                Console.WriteLine("Are we listening?");
                string path = "//home//mcje//MyRemoteApi//MyRemoteApi//localhost+2.pem";
                if (System.IO.File.Exists(path) == false)
                    Console.WriteLine("DNE");
                else
                    Console.WriteLine("pem exists");

                // Read cert and key from PEM files
                var cert = System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile("localhost+2.pem", "localhost+2-key.pem");
                listenOptions.ServerCertificate = cert;
        */
    });
    Console.WriteLine();
    Console.WriteLine("guess" + x);
        string path = "localhost+2-key.pem";
        if (System.IO.File.Exists(path) == false)
            Console.WriteLine("DNE");
        else
            Console.WriteLine("pem exists");
        Console.WriteLine();
});

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(connectionString));

builder.Services.AddControllers();
// ... rest of builder code

// Add services to the container.

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();


builder.Services.AddSwaggerGen(options =>
{
    // Locate the XML file generated by the project
    var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, xmlFilename));
});

builder.Services.AddDbContext<ApplicationDbContext>(options =>
{
    // options.UseNpgsql(builder.Configuration.GetConnectionString(defaultConnectionString));
    options.UseNpgsql(defaultConnectionString);    
    options.UseOpenIddict();
});

builder.Services.AddIdentity<IdentityUser, IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>();

builder.Services.AddOpenIddict()
    .AddCore(options =>
    {
        options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
    })
    .AddServer(options =>
    {
        options.SetAuthorizationEndpointUris("/connect/authorize")
            .SetTokenEndpointUris("/connect/token");
        options.AllowAuthorizationCodeFlow().RequireProofKeyForCodeExchange();
        options.AddDevelopmentEncryptionCertificate()
            .AddDevelopmentSigningCertificate();
        options.UseAspNetCore()
            .EnableAuthorizationEndpointPassthrough()
            .EnableTokenEndpointPassthrough();
    })
    .AddValidation(options =>
    {
        options.UseLocalServer();
        options.UseAspNetCore();
    });

// builder.Services.AddAuthentication(OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme);

builder.Services.AddAuthentication(OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme);
builder.Services.AddHostedService<SeedData>();
// 3. Understanding the OAuth Flow
Console.WriteLine("build the app!");

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}




app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();
Console.WriteLine("get ready to run");
app.Run();
